/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bancointerfaz;

import com.mycompany.bancopersistencia.conexion.Conexion;

/**
 *
 * @author USER
 */
public class Consultas extends javax.swing.JFrame {
    int id;
    Conexion conexion;
    /**
     * Creates new form Consultas
     */
    public Consultas(int id) {
        this.id=id;
        initComponents();
        setSize(600, 400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TransferenciasButton = new javax.swing.JButton();
        RetirosGeneradosButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿Qué desea consultar?");

        TransferenciasButton.setText("Transferencias");
        TransferenciasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferenciasButtonActionPerformed(evt);
            }
        });

        RetirosGeneradosButton.setText("Retiros sin cuenta");
        RetirosGeneradosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirosGeneradosButtonActionPerformed(evt);
            }
        });

        RegresarButton.setText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransferenciasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RetirosGeneradosButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(RegresarButton)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RetirosGeneradosButton)
                .addGap(18, 18, 18)
                .addComponent(TransferenciasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(RegresarButton)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetirosGeneradosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirosGeneradosButtonActionPerformed
        // TODO add your handling code here:
        HistorialRetiros h=new HistorialRetiros(id);
        h.show();
        dispose();
    }//GEN-LAST:event_RetirosGeneradosButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        PaginaPrincipal p=new PaginaPrincipal(id);
        p.show();
        dispose();
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void TransferenciasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferenciasButtonActionPerformed
        // TODO add your handling code here:
        HistorialTransferencias h=new HistorialTransferencias(id);
        h.show();
        dispose();
    }//GEN-LAST:event_TransferenciasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton RetirosGeneradosButton;
    private javax.swing.JButton TransferenciasButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
