/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bancointerfaz;

import com.mycompany.bancodominio.pojo.Cuenta;
import com.mycompany.banconegocio.control.Control;
import com.mycompany.banconegocio.excepciones.ControlException;
import com.mycompany.bancopersistencia.conexion.Conexion;
import com.mycompany.bancopersistencia.dao.CuentaDAO;
import com.mycompany.bancopersistencia.excepciones.PersistenciaException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SeleccionCuenta extends javax.swing.JFrame {
    int id;
    Control control=new Control();
    /**
     * Creates new form SeleccionCuenta
     */
    public SeleccionCuenta(int id) throws ControlException{
        this.id=id;
        initComponents();     
        this.comboCuentas(id);
        setSize(600, 400);
        setLocationRelativeTo(null);
        
        
    }
    
    public void comboCuentas(int id) throws ControlException{
        DefaultComboBoxModel<Cuenta> comboBoxModel = new DefaultComboBoxModel<>();
        
        List<Cuenta> cuentas;
        
        cuentas=control.consultarCuentasCliente(id);
        
        for (Cuenta c : cuentas) {
            comboBoxModel.addElement(c);       
        }
        CuentasComboBox.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CerrarSesionButton = new javax.swing.JButton();
        CuentasComboBox = new javax.swing.JComboBox<>();
        SeleccionarButton = new javax.swing.JButton();
        EditarButton = new javax.swing.JButton();
        AgregarCuentaButton = new javax.swing.JButton();
        AgregarFondosButton = new javax.swing.JButton();
        DesactivarCuentaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CerrarSesionButton.setText("Cerrar sesión");
        CerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionButtonActionPerformed(evt);
            }
        });

        SeleccionarButton.setText("Seleccionar");
        SeleccionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarButtonActionPerformed(evt);
            }
        });

        EditarButton.setText("Editar datos");
        EditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarButtonActionPerformed(evt);
            }
        });

        AgregarCuentaButton.setText("Agregar Cuenta");
        AgregarCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCuentaButtonActionPerformed(evt);
            }
        });

        AgregarFondosButton.setText("Agregar Fondos");
        AgregarFondosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFondosButtonActionPerformed(evt);
            }
        });

        DesactivarCuentaButton.setText("Desactivar Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(CerrarSesionButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(EditarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AgregarCuentaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AgregarFondosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SeleccionarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DesactivarCuentaButton)))
                            .addComponent(CuentasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(EditarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(CuentasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeleccionarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarCuentaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarFondosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesactivarCuentaButton)
                .addGap(47, 47, 47)
                .addComponent(CerrarSesionButton)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionButtonActionPerformed
        // TODO add your handling code here:
        InicioSesion i=new InicioSesion();
        i.show();
        dispose();
    }//GEN-LAST:event_CerrarSesionButtonActionPerformed

    private void SeleccionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarButtonActionPerformed
        // TODO add your handling code here:
        
        Cuenta c=(Cuenta)CuentasComboBox.getSelectedItem();
        PaginaPrincipal p=new PaginaPrincipal(c.getIdcuenta());
        p.show();
        dispose();
    }//GEN-LAST:event_SeleccionarButtonActionPerformed

    private void EditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            EditarDatos e = new EditarDatos(id);
            e.show();
            dispose();
        } catch (ControlException ex) {
            Logger.getLogger(SeleccionCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EditarButtonActionPerformed

    private void AgregarCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCuentaButtonActionPerformed
        // TODO add your handling code here:
        AgregarCuenta a =new AgregarCuenta(id);
        a.show();
        dispose();
        
    }//GEN-LAST:event_AgregarCuentaButtonActionPerformed

    private void AgregarFondosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFondosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarFondosButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCuentaButton;
    private javax.swing.JButton AgregarFondosButton;
    private javax.swing.JButton CerrarSesionButton;
    private javax.swing.JComboBox<Cuenta> CuentasComboBox;
    private javax.swing.JButton DesactivarCuentaButton;
    private javax.swing.JButton EditarButton;
    private javax.swing.JButton SeleccionarButton;
    // End of variables declaration//GEN-END:variables
}
